version: '3.8'
services:
  rails:
    build: ./rails
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/app
    depends_on:
      - db
  next:
    build:
      context: ./rails/next
      dockerfile: Dockerfile  # 明示的にDockerfileを指定する場合
    ports:
      - "8000:8000"
    volumes:
      - ./rails/next:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: